### PR TITLE
Login & SignUp page Impressive

### PR DESCRIPTION
**Pull request by sreevidya-16**
## Related Issue
#271 issue

## Description
Added Login and SignUp page with impressive interface

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

Screenshot (791)
Screenshot (792)

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

@Saurav-Pant, view this PR and let me know if you require any changes
Otherwise, kindly merge into main

### CODE REVIEW

**Comment by sreevidya-16** [comment]
@Saurav-Pant view this PR

**Comment by sreevidya-16** [comment]
@Saurav-Pant view this PR

**Comment by Saurav-Pant** [comment]
hey @sreevidya-16, this is not functional, UI is good but we can't use this on the application if you can make this functional using NextJS then I will merge

**Comment by sreevidya-16** [comment]
@Saurav-Pant, at the time of assigning the issue, you've not mentioned me to do it in next Js
At the last minute how do you expect me to change the code

I don't have much knowledge in next Js

I took more time to do this website
My efforts shouldn't go in vain
So decrease the level to level2 and merge into main

If you've told me atleast one day before, I would try to make any changes
You have not responded till last minute
I'm really sorry for that

Please make sure that u will mention at the start only(about ur requirements)

**Comment by Saurav-Pant** [comment]
Hey man, listen. Firstly, if you're not aware of NextJS, why did you choose this repo to contribute to? And how did I come to know that you don't know about NextJS? If you're considering a project where NextJS is used, make sure you have knowledge of it.
Secondly, I appreciate the work you've done on the UI, but think about it: this is not a static website, so just the UI will work here, where the functionality is present.
You're saying "your efforts will go in vain," but bro, contribute for learning and think practically

**Pull request closed without merging**
