### PR TITLE
added workflow as mentioned in issue #205

### LINKED ISSUE #205: feat: Auto Commenting feature for PR Merged
### What feature?

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks

### Add screenshots

PR merged

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
## Related Issue

Fixes #205 

## Description

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Asymtode712** [comment]
@Saurav-Pant I have made all the PRs for all assigned issues please review them and merge them.

Also, we would have to test some of these workflows, if they respond with some error then don't worry I would totally assist you in resolving them as I know the next steps to tackle those errors if they occur.

**Comment by Saurav-Pant** [comment]
will test and merge later Thank you for contribution, and I'll let you know they are working fine or not

**Comment by Asymtode712** [comment]
@Saurav-Pant Sure😊

**Comment by Asymtode712** [comment]
@Saurav-Pant By the time can you please assign me the other two open issues so that I can start working on them

**Review by Saurav-Pant — APPROVED** [review]
Looks Good

**Comment by Asymtode712** [comment]
@Saurav-Pant please change the 'level2' label to 'level1' label as per instructions which you might have recieved

**Pull request merged**
