### PR TITLE
Updated the toggle theme ui

### LINKED ISSUE #97: [UI] Changed Toggle Theme Button UI
If anyone has any ideas related to the Toggle Theme UI updation, please share them with me. I'll assign the task to you if your idea aligns with our needs

### PR DESCRIPTION
**Pull request by parag477**
Closes #97 
I have changed the theme switching icons and also changed the colors from black and white to nice looking colors.

col1

col2

These are the screenshots of how the colors look

### CODE REVIEW

**Comment by Saurav-Pant** [comment]
Please show me How it is looking after changes @parag477

**Comment by parag477** [comment]
Now check it.

**Comment by parag477** [comment]
Hey please review and approve my pr

**Comment by parag477** [comment]
hey @Saurav-Pant please merge it

**Review by Saurav-Pant — APPROVED** [review]
Looks Good

**Pull request merged**
