### PR TITLE
feat: provide gracefully shutdown to close safely all integration connection

### PR DESCRIPTION
**Pull request by mohammadanang**
Graceful shutdown is the process of shutting down a software application while allowing it to complete its ongoing tasks and maintain the integrity of its data. So I handled terminating the server and database safely.
For complete information [here](https://levelup.gitconnected.com/the-art-of-graceful-shutdown-in-software-applications-a27d25a4917c)
Based on the entry point file, I updated the start command server in `package.json`.
Also, manage the configuration env file to make it easier for the contributors to copy the env value & file.

### CODE REVIEW

**Comment by mohammadanang** [comment]
please review my PR here.
cc: @Saurav-Pant

**Comment by Saurav-Pant** [comment]
@mohammadanang , I will do it after some time, Thanks for contributing

**Comment by mohammadanang** [comment]
> @mohammadanang , I will do it after some time, Thanks for contributing

sure. Thanks

**Review by Saurav-Pant — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
