### PR TITLE
Added toast message

### PR DESCRIPTION
**Pull request by AyushGakre**
Fix : #174

### CODE REVIEW

**Review by Saurav-Pant — APPROVED** [review]
Looks Good

**Comment by Saurav-Pant** [comment]
can you share the video of it @AyushGakre

**Comment by AyushGakre** [comment]
@Saurav-Pant 

https://github.com/Saurav-Pant/Blood-Donation-Project/assets/122914231/445207e8-7b97-41c8-8d52-d03061f6d29c

**Comment by Saurav-Pant** [comment]
Looks Good,   Thanks @AyushGakre

**Pull request merged**
