### PR TITLE
add feature to filter location 

### LINKED ISSUE #170: feat: Adding Location to ease out filtering
### What feature?

Adding proper location (state, district, pincode etc.) in Register Donor Form 
Adding location in Find Blood page to filter out locations

### Add screenshots

Screenshot (951)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by msanchariii**
fixes #170

### CODE REVIEW

**Comment by msanchariii** [comment]
@Saurav-Pant Can you check the PR. I've attached the screenshots and details in the issue i.e. #170 .

**Comment by Saurav-Pant** [comment]
Please resolve the merge conflicts @msanchariii

**Comment by msanchariii** [comment]
@Saurav-Pant Did it.

**Comment by msanchariii** [comment]
@Saurav-Pant I resolved the conflicts again. Kindly check my PR and give feedback if anything I need to change so that I can work on next issues.

**Comment by Saurav-Pant** [comment]
It looks good @msanchariii, I will merge this later , because the model has changed so I need to properly check the changes, and you can work on another issues

**Pull request closed without merging**
