### PR TITLE
changed UI of find Cards

### PR DESCRIPTION
**Pull request by 05hiteshbansal**
## Related Issue
UI of find cards are looking odd

## Description
UI is changed with more focus on text to show issue no #251

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by 05hiteshbansal** [comment]
@Saurav-Pant please review my changes

**Comment by 05hiteshbansal** [comment]
@Saurav-Pant please review my PR

**Comment by 05hiteshbansal** [comment]
@Saurav-Pant please review my PR

**Comment by Saurav-Pant** [comment]
Hey @05hiteshbansal , the UI is not looking cool, so for now I am closing this

**Pull request closed without merging**
