### PR TITLE
fix: 🐛 No error showing after submit form in donorform page

### PR DESCRIPTION
**Pull request by growupanand**
✅ Closes: #142

**Screenshots**

image

image

### CODE REVIEW

**Comment by growupanand** [comment]
@Saurav-Pant can you please merge the PR if everything looks good? Thanks

**Review by Saurav-Pant — APPROVED** [review]

**Comment by growupanand** [comment]
@Saurav-Pant, I see my changes are not in production. Is there any specific reason for that?

**Comment by Saurav-Pant** [comment]
Yeah, I reverted the changes because you removed formik from the Form but we needed Formik for now

**Comment by growupanand** [comment]
Please check my changes again, I think you had some confusion. I have not removed Formik.

**Old code**
```
import { useFormik } from "formik";
```

**New code**
```
import { ErrorMessage, FastField, Form, Formik, FormikHelpers } from "formik";
```


As you can see I am using same library, and if you see my code it is more structured and readable then previous.

**Comment by Saurav-Pant** [comment]
sorry @growupanand , can you please create another PR for these changes.

**Comment by growupanand** [comment]
> sorry @growupanand , can you please create another PR for these changes.

@Saurav-Pant here is the PR - https://github.com/Saurav-Pant/Blood-Donation-Project/pull/183

**Comment by Saurav-Pant** [comment]
I'll definitely merge after some time, can you please share the video about how it's working after changes?

**Comment by growupanand** [comment]
I see you have deployed on Vercel. A better approach here would be to see it live on a Vercel Preview build. Vercel Preview is a feature of Vercel that allows you to view and test changes before they go live.

image

**Pull request merged**
